#! /bin/bash

if [ -z "$JEKYLL_SITE_DIR" ]
then
	echo "You must set JEKYLL_SITE_DIR before using this"
	exit 1
fi

builtin cd $JEKYLL_SITE_DIR

git add --all .
echo "### IMPORTANT ###"
echo "The following are changes are about to be committed:"
git status

echo "Do you wish to commit these changes to your site?"
select yn in "Yes" "No"; do
	case $yn in
		Yes ) break;;
		No ) echo "Unstaging changes."; git reset HEAD . ; exit 1;;
	esac
done

read -p "Enter a commit message: " COMMIT_MESSAGE
git commit -m "$COMMIT_MESSAGE"

echo "Pushing to GitHub Pages."
git push
echo "GitHub site updated."
