#!/usr/bin/env bash

INSTALL_DIR="/usr/local/bin"
WORKING_DIR=`pwd`

function install_file() {
	if [ -f "$INSTALL_DIR/$1" ]
	then
		echo "Removing old symlink at $INSTALL_DIR/$1"
		rm "$INSTALL_DIR/$1"
	fi

	echo "Symlinking $WORKING_DIR/$file  to $INSTALL_DIR/$1"
	ln -s "$WORKING_DIR/$file" "$INSTALL_DIR/$1"
}

find * ! -iname "install" | while read file; do install_file "$file"; done
