#!/usr/bin/env bash

# Set to what directory you want to temporarily keep files
OUTPUT_DIR=/mnt/torrents/tmp

# Set up for SickBeard & CouchPotato
SB_HOST="localhost"
SB_PORT="8081"
SB_USER=""
SB_PASS=""

CP_HOST="localhost"
CP_PORT="5050"
CP_KEY=""

# Auto decompress rar files, 1 enables, 0 disables
ENABLE_DECOMPRESS=1

# One of "hard", "soft", and "copy"
DOOP_STYLE="hard"

SB_CATEGORY="tv-shows"
CP_CATEGORY="movies"

COMPRESSED_EXTS[0]="rar"
COMPRESSED_EXTS[1]=".1"
COMPRESSED_EXTS[2]=".01"
COMPRESSED_EXTS[3]=".001"

# Change this if unrar isn't on the PATH variable
UNRAR_CMD=`which unrar`

function doop_file() {
        if [ "$DOOP_STYLE" = "hard" ]
        then
                ln "$1" $OUTPUT_DIR
        elif [ "$DOOP_STYLE" = "soft" ]
        then
                ln -s "$1" $OUTPUT_DIR
        else
                cp "$1" $OUTPUT_DIR
        fi
        }

function test_extension() {
        for ext in $2
        do

        if [ "$1" = "$ext" ]
        then
                return 0
        fi
        done
        return 1
}

function process_file() {
        extension=`echo "$1"|awk -F . '{print $NF}'`

        if [ $ENABLE_DECOMPRESS -eq 1 ] && test_extension "$extension" $COMPRESSED_EXTS
        then
                $UNRAR_CMD x -o+ -y -idp "$1" >> unrar.log
        else
                doop_file "$1"
        fi
}

function main() {
        CATEGORY="other"
        OIFS=$IFS
        IFS='/'
        for dir in $TR_TORRENT_DIR
        do
                if [ "$dir" = "$SB_CATEGORY" ]
                then
                        CATEGORY=$SB_CATEGORY
                elif [ "$dir" = "$CP_CATEGORY" ]
                then
                        CATEGORY=$CP_CATEGORY
                fi
        done
        IFS=$OIFS

        REAL_ROOT="$TR_TORRENT_DIR/$TR_TORRENT_NAME"
        OUTPUT_DIR="$OUTPUT_DIR/$CATEGORY"
        echo "Got torrent '$REAL_ROOT'."
        if [ ! -f $REAL_ROOT ]
        then
                echo "Torrent is directory, creating sub-folder."
                OUTPUT_DIR="$OUTPUT_DIR/$TR_TORRENT_NAME"
        fi

        mkdir -p $OUTPUT_DIR
        builtin cd $OUTPUT_DIR

        echo "Processing files."
        # Process files into temp directory
        for file in $(find "$REAL_ROOT" -type f)
        do
                process_file "$file"
        done

        # Send update to either SB or CP
        # if [ "$CATEGORY" = "$SB_CATEGORY" ]
        # then
        #         SB_URL="http://$SB_HOST:$SB_PORT/home/postprocess/processEpisode"
        #         SB_DATA="episodeDir=`urlencode $OUTPUT_DIR`"
        #         wget --post-data="$SB_DATA" "$SB_URL"
        # if ["$CATEGORY" = "$CP_CATEGORY" ]
        # then
        #         CP_URL="http://$CP_HOST:$CP_PORT/api/$CP_KEY"
        #         CP_CMD="renamer.scan/?movie_folder=$OUTPUT_DIR"
        #         wget "$CP_URL/$CP_CMD"
        # fi
}

main >> "$OUTPUT_DIR/postprocessing.log" 2>&1