#!/usr/bin/env bash

# Set to what directory you want to temporarily keep files
TEMP_DIR=/mnt/tmp
LOG_FILE="$TEMP_DIR/postprocessing.log"

# Set up for SickBeard & CouchPotato
SB_HOST="localhost"
SB_PORT="8081"
SB_USER=""
SB_PASS=""

CP_HOST="localhost"
CP_PORT="5050"
CP_KEY=""

# Auto decompress rar files, 1 enables, 0 disables
ENABLE_DECOMPRESS=1

# One of "hard", "soft", and "copy"
DOOP_STYLE="hard"

SB_CATEGORY="tv-shows"
CP_CATEGORY="movies"

COMPRESSED_EXTS[0]="rar"
COMPRESSED_EXTS[1]=".1"
COMPRESSED_EXTS[2]=".01"
COMPRESSED_EXTS[3]=".001"

# Change this if unrar isn't on the PATH variable
UNRAR_CMD=`which unrar`

function doop_file() {
        if [ "$DOOP_STYLE" = "hard" ]
        then
                ln "$1" "$OUTPUT_DIR"
        elif [ "$DOOP_STYLE" = "soft" ]
        then
                ln -s "$1" "$OUTPUT_DIR"
        else
                cp "$1" "$OUTPUT_DIR"
        fi
        }

function test_extension() {
        for ext in $2
        do

        if [ "$1" = "$ext" ]
        then
                return 0
        fi
        done
        return 1
}

function process_file() {
        echo "Processing file '$1'"
        extension=`echo "$1"|awk -F . '{print $NF}'`

        if [ $ENABLE_DECOMPRESS -eq 1 ] && test_extension "$extension" $COMPRESSED_EXTS
        then
                $UNRAR_CMD x -o+ -y -idp "$1" >> unrar.log
        else
                doop_file "$1"
        fi
}

function main() {
        echo "====== Starting Transmission To Media ======"
        echo "Torrent directory: '$TR_TORRENT_DIR'."
        echo "Torrent name: '$TR_TORRENT_NAME'."

        REAL_ROOT="$TR_TORRENT_DIR/$TR_TORRENT_NAME"
        echo "Real file: '$REAL_ROOT'."

        CATEGORY="other"
        OIFS=$IFS
        IFS='/'
        for dir in $TR_TORRENT_DIR
        do
                if [ "$dir" = "$SB_CATEGORY" ]
                then
                        CATEGORY=$SB_CATEGORY
                elif [ "$dir" = "$CP_CATEGORY" ]
                then
                        CATEGORY=$CP_CATEGORY
                fi
        done
        IFS=$OIFS
        echo "Category is '$CATEGORY'."

        OUTPUT_DIR="$TEMP_DIR/$CATEGORY"

        builtin cd $TR_TORRENT_DIR
        if [[ ! -f $TR_TORRENT_NAME ]]
        then
                echo "Torrent is directory, creating sub-folder."
                OUTPUT_DIR="$OUTPUT_DIR/$TR_TORRENT_NAME"
        fi

        mkdir -p "$OUTPUT_DIR"
        builtin cd "$OUTPUT_DIR"

        # Process files into temp directory
        echo "Finding files under torrent name."
        find "$REAL_ROOT" -type f | while read file; do process_file "$file"; done

        # Send update to either SB or CP
        if [ "$CATEGORY" = "$SB_CATEGORY" ]
        then
                SB_URL="http://$SB_HOST:$SB_PORT/home/postprocess/processEpisode"
                SB_DATA="dir=`urlencode $OUTPUT_DIR`"
                wget --user=$SB_USER --password=$SB_PASS --post-data="$SB_DATA" "$SB_URL" -O /dev/null
        elif ["$CATEGORY" = "$CP_CATEGORY" ]
        then
                CP_URL="http://$CP_HOST:$CP_PORT/api/$CP_KEY"
                CP_CMD="renamer.scan/?movie_folder=$OUTPUT_DIR"
                wget "$CP_URL/$CP_CMD"
        fi

        # Delete empty folders
        builtin cd "$TEMP_DIR"
        find * -depth -type d -empty -delete
}

main >> "$LOG_FILE" 2>&1